{-# LANGUAGE OverloadedStrings #-}

-- | The names GHC 9.12 writes into interface files as keys that fixities
-- depend on.
--
-- Generated by @generate-known-keys.py@ in the root of the repository, from
-- GHC 9.12.2. Run that script again to update this table.
module Tilia.Fixity.KnownKeys.Ghc912
  ( knownKeys,
  )
where

import Data.Text (Text)
import Tilia.Fixity (Namespace (..))

-- | Every operator a key stands for that has a fixity, and every type or
-- class that carries one: the tag and index of its key, its namespace, the
-- module GHC prints it with, if it prints one, and its name.
knownKeys :: [(Char, Int, Namespace, Maybe Text, Text)]
knownKeys =
  [ ('0', 4, InTerms, Just "GHC.Internal.Base", "++"),
    ('0', 8, InTerms, Just "GHC.Prim", "seq"),
    ('0', 123, InTerms, Just "GHC.Internal.Base", "$"),
    ('0', 161, InTerms, Just "GHC.Internal.Num", "-"),
    ('0', 167, InTerms, Just "GHC.Classes", "=="),
    ('0', 168, InTerms, Just "GHC.Classes", ">="),
    ('0', 171, InTerms, Just "GHC.Internal.Base", ">>="),
    ('0', 172, InTerms, Just "GHC.Internal.Base", ">>"),
    ('0', 184, InTerms, Just "GHC.Internal.Control.Arrow", "|||"),
    ('0', 554, InTerms, Just "GHC.Internal.Base", "<>"),
    ('0', 751, InTerms, Just "GHC.Internal.Base", "<*>"),
    ('0', 753, InTerms, Just "GHC.Internal.Base", "*>"),
    ('2', 3, InTypes, Just "GHC.Classes", "Eq"),
    ('2', 5, InTypes, Just "GHC.Internal.Float", "Floating"),
    ('2', 6, InTypes, Just "GHC.Internal.Real", "Fractional"),
    ('2', 7, InTypes, Just "GHC.Internal.Real", "Integral"),
    ('2', 8, InTypes, Just "GHC.Internal.Base", "Monad"),
    ('2', 10, InTypes, Just "GHC.Internal.Base", "Functor"),
    ('2', 11, InTypes, Just "GHC.Internal.Num", "Num"),
    ('2', 12, InTypes, Just "GHC.Classes", "Ord"),
    ('2', 34, InTypes, Just "GHC.Internal.Base", "Applicative"),
    ('2', 35, InTypes, Just "GHC.Internal.Data.Foldable", "Foldable"),
    ('2', 47, InTypes, Just "GHC.Internal.Base", "Semigroup"),
    ('3', 80, InTypes, Just "GHC.Types", "~"),
    ('3', 82, InTypes, Just "GHC.Types", "~~"),
    ('3', 172, InTypes, Just "GHC.Internal.Base", "NonEmpty"),
    ('3', 282, InTypes, Just "GHC.Internal.Generics", ":+:"),
    ('3', 284, InTypes, Just "GHC.Internal.Generics", ":*:"),
    ('3', 286, InTypes, Just "GHC.Internal.Generics", ":.:"),
    ('3', 804, InTypes, Just "GHC.Internal.TypeNats", "+"),
    ('3', 806, InTypes, Just "GHC.Internal.TypeNats", "*"),
    ('3', 808, InTypes, Just "GHC.Internal.TypeNats", "^"),
    ('3', 810, InTypes, Just "GHC.Internal.TypeNats", "-"),
    ('3', 820, InTypes, Just "GHC.Internal.TypeNats", "Div"),
    ('3', 822, InTypes, Just "GHC.Internal.TypeNats", "Mod"),
    ('6', 6, InTerms, Nothing, ":"),
    ('6', 7, InTerms, Just "GHC.Types", ":"),
    ('6', 153, InTerms, Just "GHC.Internal.TypeError", ":<>:"),
    ('6', 156, InTerms, Just "GHC.Internal.TypeError", ":$$:"),
    ('9', 330, InTerms, Just "GHC.Prim", "+#"),
    ('9', 332, InTerms, Just "GHC.Prim", "-#"),
    ('9', 334, InTerms, Just "GHC.Prim", "*#"),
    ('9', 360, InTerms, Just "GHC.Prim", ">#"),
    ('9', 362, InTerms, Just "GHC.Prim", ">=#"),
    ('9', 364, InTerms, Just "GHC.Prim", "==#"),
    ('9', 366, InTerms, Just "GHC.Prim", "/=#"),
    ('9', 368, InTerms, Just "GHC.Prim", "<#"),
    ('9', 370, InTerms, Just "GHC.Prim", "<=#"),
    ('9', 518, InTerms, Just "GHC.Prim", ">##"),
    ('9', 520, InTerms, Just "GHC.Prim", ">=##"),
    ('9', 522, InTerms, Just "GHC.Prim", "==##"),
    ('9', 524, InTerms, Just "GHC.Prim", "/=##"),
    ('9', 526, InTerms, Just "GHC.Prim", "<##"),
    ('9', 528, InTerms, Just "GHC.Prim", "<=##"),
    ('9', 534, InTerms, Just "GHC.Prim", "+##"),
    ('9', 536, InTerms, Just "GHC.Prim", "-##"),
    ('9', 538, InTerms, Just "GHC.Prim", "*##"),
    ('9', 540, InTerms, Just "GHC.Prim", "/##"),
    ('9', 584, InTerms, Just "GHC.Prim", "**##")
  ]
